name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.23.1
  - ipython=8.0.1
  - notebook=6.4.8
  - jupyterlab=3.2.9
  - cookiecutter=1.7.3
  - hydra-core=1.1.1
  - matplotlib=3.5.1
  - pandas=1.4.1
  - git=2.35.1
  - pip=22.0.3
  - pip:
      - wandb==0.12.10
